spring:
  application:
    name: ms-gateway
  cloud:
    compatibility-verifier:
      enabled: false #Para la compatibilidad con Spring Cloud Gateway y Spring Boot 3.x
    gateway:
      # Configuración de CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"      # Frontend React
              - "http://localhost:4200"      # Frontend Angular
            allowedMethods:
              - GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: "*"
            allow-credentials: true
            max-age: 3600

      # Configuración de rutas de los microservicios
      routes:
        - id: ms-usuarios-route           # Nombre único 1
          uri: lb://ms-usuarios           # Destino dinámico (Eureka)
          predicates:
            - Path=/api/usuarios/** # Ruta de controllers del microservicio

        - id: ms-catalogo-route           #2
          uri: lb://ms-catalogo
          predicates:
            - Path=/api/producto/**

        - id: ms-inventario-route         #3
          uri: lb://ms-inventario
          predicates:
            - Path=/api/movimientos/**, /api/stock/**

        - id: ms-carrito-route            #4
          uri: lb://ms-carrito
          predicates:
            - Path=/api/carrito/**

        - id: ms-compatibilidad-route     #5
          uri: lb://ms-compatibilidad
          predicates:
            - Path=/api/compatibilidad/**

        - id: ms-pedidos-route            #6
          uri: lb://ms-pedidos
          predicates:
            - Path=/api/pedidos/**

        - id: ms-ensamblajes-route        #7
          uri: lb://ms-ensamblajes
          predicates:
            - Path=/api/ensamblajes/**,/api/fases/**

        - id: ms-pagos-route              #8
          uri: lb://ms-pagos
          predicates:
            - Path=/api/pagos/**

        - id: ms-despachos-route          #9
          uri: lb://ms-despachos
          predicates:
            - Path=/api/despachos/**

        - id: ms-notificaciones-route     #10
          uri: lb://ms-notificaciones
          predicates:
            - Path=/api/notificaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8080